[INFO     2010-08-31 13:37:04,491 bulkloader.py] Logging to bulkloader-log-20100831.133704
[INFO     2010-08-31 13:37:04,491 bulkloader.py] Throttling transfers:
[INFO     2010-08-31 13:37:04,491 bulkloader.py] Bandwidth: 250000 bytes/second
[INFO     2010-08-31 13:37:04,491 bulkloader.py] HTTP connections: 8/second
[INFO     2010-08-31 13:37:04,491 bulkloader.py] Entities inserted/fetched/modified: 20/second
[INFO     2010-08-31 13:37:04,492 bulkloader.py] Batch Size: 10
[INFO     2010-08-31 13:37:04,515 bulkloader.py] Opening database: bulkloader-progress-20100831.133704.sql3
[DEBUG    2010-08-31 13:37:04,532 adaptive_thread_pool.py] [Thread-1] WorkerThread: started
[DEBUG    2010-08-31 13:37:04,542 adaptive_thread_pool.py] [Thread-2] WorkerThread: started
[DEBUG    2010-08-31 13:37:04,553 adaptive_thread_pool.py] [Thread-3] WorkerThread: started
[DEBUG    2010-08-31 13:37:04,563 adaptive_thread_pool.py] [Thread-4] WorkerThread: started
[DEBUG    2010-08-31 13:37:04,573 adaptive_thread_pool.py] [Thread-5] WorkerThread: started
[DEBUG    2010-08-31 13:37:04,584 adaptive_thread_pool.py] [Thread-6] WorkerThread: started
[DEBUG    2010-08-31 13:37:04,594 adaptive_thread_pool.py] [Thread-7] WorkerThread: started
[DEBUG    2010-08-31 13:37:04,604 adaptive_thread_pool.py] [Thread-8] WorkerThread: started
[DEBUG    2010-08-31 13:37:04,615 adaptive_thread_pool.py] [Thread-9] WorkerThread: started
[DEBUG    2010-08-31 13:37:04,625 adaptive_thread_pool.py] [Thread-10] WorkerThread: started
[DEBUG    2010-08-31 13:37:04,636 bulkloader.py] Configuring remote_api. url_path = /remote_api, servername = mk10koers.appspot.com
[DEBUG    2010-08-31 13:37:05,103 bulkloader.py] Bulkloader using app_id: mk10koers
[INFO     2010-08-31 13:37:05,104 bulkloader.py] Connecting to mk10koers.appspot.com/remote_api
[DEBUG    2010-08-31 13:37:05,508 bulkloader.py] [Thread-11] ProgressTrackerThread: started
[DEBUG    2010-08-31 13:37:05,519 bulkloader.py] [Thread-12] DataSourceThread: started
[INFO     2010-08-31 13:37:05,519 bulkloader.py] Starting import; maximum 10 entities per post
[DEBUG    2010-08-31 13:37:05,533 adaptive_thread_pool.py] [Thread-1] Got work item [1-10]
[DEBUG    2010-08-31 13:37:05,541 bulkloader.py] [Thread-12] DataSourceThread: exiting
[DEBUG    2010-08-31 13:37:05,622 bulkloader.py] Waiting for worker threads to finish...
[ERROR    2010-08-31 13:37:05,632 adaptive_thread_pool.py] [Thread-1] WorkerThread:
Traceback (most recent call last):
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/adaptive_thread_pool.py", line 150, in WorkOnItems
    status, instruction = item.PerformWork(self.__thread_pool)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/bulkloader.py", line 691, in PerformWork
    transfer_time = self._TransferItem(thread_pool)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/bulkloader.py", line 846, in _TransferItem
    self.content = self.request_manager.EncodeContent(self.rows)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/bulkloader.py", line 1267, in EncodeContent
    entity = loader.create_entity(values, key_name=key, parent=parent)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/bulkloader.py", line 2522, in create_entity
    properties[name] = converter(val)
  File "coureurloader.py", line 25, in <lambda>
    [('timestamp', lambda x: datetime.datetime.strptime(x, '%m/%d/%Y').date()),
  File "/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/_strptime.py", line 330, in strptime
    (data_string, format))
ValueError: time data did not match format:  data=Tijdstempel  fmt=%m/%d/%Y
[DEBUG    2010-08-31 13:37:05,656 adaptive_thread_pool.py] [Thread-1] WorkerThread: exiting
[INFO     2010-08-31 13:37:05,656 adaptive_thread_pool.py] [Thread-2] Backing off due to errors: 1.0 seconds
[INFO     2010-08-31 13:37:06,132 bulkloader.py] An error occurred. Shutting down...
[DEBUG    2010-08-31 13:37:06,134 adaptive_thread_pool.py] [Thread-5] WorkerThread: exiting
[DEBUG    2010-08-31 13:37:06,134 adaptive_thread_pool.py] [Thread-3] WorkerThread: exiting
[DEBUG    2010-08-31 13:37:06,134 adaptive_thread_pool.py] [Thread-4] WorkerThread: exiting
[DEBUG    2010-08-31 13:37:06,135 adaptive_thread_pool.py] [Thread-6] WorkerThread: exiting
[DEBUG    2010-08-31 13:37:06,135 adaptive_thread_pool.py] [Thread-7] WorkerThread: exiting
[DEBUG    2010-08-31 13:37:06,135 adaptive_thread_pool.py] [Thread-8] WorkerThread: exiting
[DEBUG    2010-08-31 13:37:06,136 adaptive_thread_pool.py] [Thread-9] WorkerThread: exiting
[DEBUG    2010-08-31 13:37:06,136 adaptive_thread_pool.py] [Thread-10] WorkerThread: exiting
[DEBUG    2010-08-31 13:37:06,137 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2010-08-31 13:37:06,137 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2010-08-31 13:37:06,156 adaptive_thread_pool.py] [Thread-2] WorkerThread: exiting
[DEBUG    2010-08-31 13:37:06,157 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2010-08-31 13:37:06,157 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2010-08-31 13:37:06,157 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2010-08-31 13:37:06,157 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2010-08-31 13:37:06,157 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2010-08-31 13:37:06,158 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2010-08-31 13:37:06,158 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2010-08-31 13:37:06,158 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[ERROR    2010-08-31 13:37:06,158 adaptive_thread_pool.py] Error in Thread-1: time data did not match format:  data=Tijdstempel  fmt=%m/%d/%Y
[DEBUG    2010-08-31 13:37:06,159 adaptive_thread_pool.py] Traceback (most recent call last):
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/adaptive_thread_pool.py", line 150, in WorkOnItems
    status, instruction = item.PerformWork(self.__thread_pool)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/bulkloader.py", line 691, in PerformWork
    transfer_time = self._TransferItem(thread_pool)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/bulkloader.py", line 846, in _TransferItem
    self.content = self.request_manager.EncodeContent(self.rows)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/bulkloader.py", line 1267, in EncodeContent
    entity = loader.create_entity(values, key_name=key, parent=parent)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/bulkloader.py", line 2522, in create_entity
    properties[name] = converter(val)
  File "coureurloader.py", line 25, in <lambda>
    [('timestamp', lambda x: datetime.datetime.strptime(x, '%m/%d/%Y').date()),
  File "/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/_strptime.py", line 330, in strptime
    (data_string, format))
ValueError: time data did not match format:  data=Tijdstempel  fmt=%m/%d/%Y

[DEBUG    2010-08-31 13:37:06,169 bulkloader.py] Waiting for progress_thread to terminate...
[DEBUG    2010-08-31 13:37:06,175 bulkloader.py] [Thread-11] ProgressTrackerThread: exiting
[DEBUG    2010-08-31 13:37:06,180 bulkloader.py] ... done.
[INFO     2010-08-31 13:37:06,180 bulkloader.py] 13 entites total, 0 previously transferred
[INFO     2010-08-31 13:37:06,180 bulkloader.py] 0 entities (724 bytes) transferred in 1.7 seconds
[INFO     2010-08-31 13:37:06,180 bulkloader.py] Some entities not successfully transferred
